Feature/it hurts because its good
Dutesier/webserv pull request #27
Opened 2023-01-11 16:06 UTC by mlanca-c

Things I did:

* Changed everything I could to smart pointers
* Changed class attribute names to start with m_ (just like duarte does it)
* Changed Config.hpp (This is the config parsing I did, I just changed my code and this doesn't affect what were doing at all)
* formatted code with .clang-format

What we have for now:
* The program passes all tests
* No leaks (obviously)
* Cleaner code

2023-01-11 18:03 UTC, Dutesier requested changes
clang-format is a double edge sword :)

2023-01-11 18:03 UTC, Dutesier commented on tests/test_HTTPParser.cpp
> +//     this->client->send_message("GET /usr/home
Nope, this will not compile once uncommented

2023-01-11 18:20 UTC, J0Santos commented on srcs/utils/utils.cpp
> +    static std::string root = d_path() + "website/";
https://stackoverflow.com/questions/1005685/c-static-initialization-order

Nope, no guarantee...if we want to do this, it seems we have to wrap it in a function...

2023-01-11 18:30 UTC, J0Santos commented on srcs/utils/utils.cpp
> +    static std::string root = d_path() + "website/";
but this is for static vars in 2 different files, not sure if it works on when on the same file

2023-01-11 18:43 UTC, J0Santos commented on srcs/utils/utils.cpp
> +    static std::string root = d_path() + "website/";
https://stackoverflow.com/questions/38148438/c-static-initialization-order-fiasco-happens-when

Its not a problem

2023-01-12 11:49 UTC, Dutesier approved these changes

2023-01-12 11:49 UTC, merged